// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjSE2Hjv9t3BvYOaQBTQCt8jOMh333op0',
    appId: '1:1008276007753:web:1016aacb1c2617590ec898',
    messagingSenderId: '1008276007753',
    projectId: 'connectonic-live',
    authDomain: 'connectonic-live.firebaseapp.com',
    databaseURL: 'https://connectonic-live-default-rtdb.firebaseio.com',
    storageBucket: 'connectonic-live.firebasestorage.app',
    measurementId: 'G-CCSH0WNTQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn7JtXmy5e20B9xpwIX-8Dn5MRq1CAsn0',
    appId: '1:1008276007753:android:5459ea10b39cd7940ec898',
    messagingSenderId: '1008276007753',
    projectId: 'connectonic-live',
    databaseURL: 'https://connectonic-live-default-rtdb.firebaseio.com',
    storageBucket: 'connectonic-live.firebasestorage.app',
  );
}
